config: |
  [secrets]
  backend = airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend
  backend_kwargs = {
    "connections_prefix": "Airflow/connections",
    "variables_prefix": "Airflow/variables",
    "config_prefix": "Airflow/config",
    "profile_name": "default"
  }
