name: Deploy Helm Chart
permissions: read-all

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_digest:
        required: true
        type: string

jobs:
  helm_deploy:
      name: Deploy helm chart
      environment: ${{ inputs.environment }}
      runs-on: ubuntu-latest
      steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@d4fffb50872869abe2d9a9098a6d9c5aa7d16be4 # v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519 # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      
      - name: Setup WireGuard
        run:  |
          sudo apt install wireguard
          echo "${{ secrets.WIREGUARD_PRIVATE_KEY }}" > privatekey
          sudo ip link add dev wg1 type wireguard
          sudo ip address add dev wg1 ${{ secrets.WIREGUARD_OVERLAY_NETWORK_IP }} peer ${{ secrets.SSH_TARGET_IP }}
          sudo wg set wg1 listen-port 48123 private-key privatekey peer ${{ secrets.WIREGUARD_PEER_PUBLIC_KEY }} allowed-ips 0.0.0.0/0 endpoint ${{ secrets.WIREGUARD_ENDPOINT }}
          sudo ip link set up dev wg1

      - name: Install Helm Chart
        run: |
          scp ${{ secrets.SSH_USER }}@${{ secrets.SSH_TARGET_IP }}:~/.kube/config ./
          helm repo add apache-airflow https://airflow.apache.org
          helm upgrade \
            airflow \
            apache-airflow/airflow \
            --install \
            --kubeconfig ./config \
            --kube-apiserver https://${{ secrets.SSH_TARGET_IP }}:6443 \
            --create-namespace  \
            -n airflow \
            --set executor="KubernetesExecutor" \
            --set dags.persistence.enabled="false" \
            --set triggerer.persistence.size="10Gi" \
            --set logs.persistence.enabled="true" \
            --set logs.persistence.size="10Gi" \
            --set dags.gitSync.enabled="true" \
            --set dags.gitSync.repo="https://github.com/nycmeshnet/nycmesh-airflow.git" \
            --set dags.gitSync.branch="james/init" \
            --set dags.gitSync.subPath="dags" \
            --set apiServer.service.type="NodePort" \
            --set apiServer.service.ports[0].port="8080" \
            --set apiServer.service.ports[0].targetPort="8080" \
            --set apiServer.service.ports[0].nodePort="30002" \
            --set apiServer.service.ports[0].protocol="TCP" \
            --set apiServer.service.ports[0].name="http" \
            --set apiServer.defaultUser.enabled="true" \
            --set apiServer.defaultUser.email="jameso+airflowapi@nycmesh.net" \
            --set apiServer.defaultUser.username="admin" \
            --set apiServer.defaultUser.password="${{ secrets.AIRFLOW_ADMIN_PASSWORD }}" \
            --set webserver.defaultUser.enabled="true" \
            --set webserver.defaultUser.email="jameso+airflowweb@nycmesh.net" \
            --set webserver.defaultUser.username="admin" \
            --set webserver.defaultUser.password="${{ secrets.AIRFLOW_ADMIN_PASSWORD }}" \
            --set webserver.startupProbe.failureThreshold="60" \
            --set webserverSecretKey="${{ secrets.AIRFLOW_SECRET_KEY }}" \
            --set fernetKey="${{ secrets.AIRFLOW_FERNET_KEY }}" \
            --set defaultAirflowRepository="jamesomesh/airflow" \
            --set defaultAirflowDigest="${{ inputs.image_digest }}" \
            --set images.pod_template.pullPolicy="Always" \
            -f infra/extra.yaml

          # Rolling restart
          kubectl --kubeconfig ./config --server https://${{ secrets.SSH_TARGET_IP }}:6443 -n airflow rollout restart deploy
          kubectl --kubeconfig ./config --server https://${{ secrets.SSH_TARGET_IP }}:6443 -n airflow rollout restart statefulset
